import { cookies } from 'next/headers';
import { verifyToken } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { SignInPrompt } from '@/components/layouts/sign-in-prompt';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Button } from '@/components/ui/button';
import {
  ArrowLeft, FileText, Brain, Calendar, MessageSquare,
  AlertCircle, Sparkles, CheckCircle2, BookOpen,
  ChevronRight, AlertTriangle, Clock, Scale,
} from 'lucide-react';

interface AiData {
  keyFacts?: string[];
  recommendedActions?: string[];
  caseReferences?: { name: string; year: string; court: string; relevance: string }[];
  coreIssue?: string;
  estimatedComplexity?: string;
  urgencyReasoning?: string;
  riskFactors?: string[];
  timeConstraints?: string[];
}

export default async function CaseDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  const cookieStore = await cookies();
  const token = cookieStore.get('lawsphere_token')?.value;
  let userId: string;
  try {
    if (!token) throw new Error();
    userId = verifyToken(token).sub;
  } catch {
    return <SignInPrompt message="Sign in to view case details" />;
  }

  const clientProfile = await prisma.clientProfile.findUnique({ where: { userId } });
  if (!clientProfile) return <SignInPrompt message="Sign in to view case details" />;

  const legalCase = await prisma.case.findUnique({
    where: { id },
    include: {
      practiceArea: true,
      recommendations: {
        orderBy: { rank: 'asc' },
        take: 5,
        include: {
          lawyerProfile: {
            include: {
              practiceAreas: { include: { practiceArea: true }, take: 2 },
            },
          },
        },
      },
    },
  });

  if (!legalCase || legalCase.clientProfileId !== clientProfile.id) return notFound();

  const urgencyColor: Record<string, string> = {
    CRITICAL: 'bg-red-100 text-red-700',
    HIGH: 'bg-orange-100 text-orange-700',
    MEDIUM: 'bg-yellow-100 text-yellow-700',
    LOW: 'bg-green-100 text-green-700',
  };
  const statusColor: Record<string, string> = {
    MATCHED: 'bg-indigo-100 text-indigo-700',
    IN_CONSULTATION: 'bg-emerald-100 text-emerald-700',
    SUBMITTED: 'bg-blue-100 text-blue-700',
    DRAFT: 'bg-slate-100 text-slate-500',
  };
  const complexityColor: Record<string, string> = {
    simple: 'bg-green-100 text-green-700',
    moderate: 'bg-yellow-100 text-yellow-700',
    complex: 'bg-red-100 text-red-700',
  };

  const ai = (legalCase.aiExtractedEntities ?? {}) as AiData;
  const hasAnalysis = !!legalCase.aiSummary;

  return (
    <div className="space-y-6 max-w-5xl">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Link href="/client/cases" className="p-2 rounded-xl hover:bg-slate-100 transition-colors">
          <ArrowLeft className="h-5 w-5 text-slate-500" />
        </Link>
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-slate-900">{legalCase.title}</h1>
          <div className="flex flex-wrap items-center gap-2 mt-1">
            <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${urgencyColor[legalCase.urgency] ?? ''}`}>{legalCase.urgency}</span>
            <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${statusColor[legalCase.status] ?? 'bg-slate-100 text-slate-600'}`}>{legalCase.status.replace('_', ' ')}</span>
            {legalCase.practiceArea && <span className="text-xs text-slate-400">{legalCase.practiceArea.name}</span>}
            <span className="text-xs text-slate-400">#{legalCase.caseNumber}</span>
          </div>
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* Main column */}
        <div className="lg:col-span-2 space-y-5">

          {/* Description */}
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
            <div className="flex items-center gap-2 mb-4">
              <FileText className="h-5 w-5 text-slate-400" />
              <h2 className="font-semibold text-slate-900">Case Description</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed">{legalCase.description}</p>
          </div>

          {/* AI Analysis */}
          {hasAnalysis ? (
            <div className="bg-white rounded-2xl border border-indigo-100 shadow-sm overflow-hidden">
              {/* Header */}
              <div className="flex items-center gap-3 px-6 py-4 border-b border-indigo-100 bg-indigo-50/50">
                <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center shrink-0">
                  <Brain className="h-4 w-4 text-white" />
                </div>
                <div className="flex-1">
                  <h2 className="font-semibold text-slate-900">AI Legal Analysis</h2>
                  <p className="text-xs text-slate-500">Generated by GPT-4o · {new Date(legalCase.updatedAt).toLocaleDateString('en-IN')}</p>
                </div>
                <span className="text-xs bg-indigo-100 text-indigo-700 px-2.5 py-1 rounded-full font-medium flex items-center gap-1">
                  <Sparkles className="h-3 w-3" />GPT-4o
                </span>
              </div>

              <div className="p-6 space-y-6">
                {/* Summary */}
                <div>
                  <p className="text-sm text-slate-700 leading-relaxed">{legalCase.aiSummary}</p>
                  {ai.coreIssue && (
                    <div className="mt-3 flex items-start gap-2 bg-slate-50 rounded-xl p-3">
                      <Scale className="h-4 w-4 text-indigo-500 shrink-0 mt-0.5" />
                      <p className="text-sm font-medium text-slate-700">{ai.coreIssue}</p>
                    </div>
                  )}
                </div>

                {/* Risk / urgency */}
                {(legalCase.urgency === 'CRITICAL' || legalCase.urgency === 'HIGH') && (
                  <div className="flex items-start gap-2.5 p-4 bg-red-50 rounded-xl border border-red-100">
                    <AlertCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />
                    <div>
                      <p className="text-sm font-semibold text-red-700 mb-1">{legalCase.urgency === 'CRITICAL' ? 'Critical — Immediate action required' : 'High urgency — Act within a week'}</p>
                      {ai.urgencyReasoning && <p className="text-xs text-red-600">{ai.urgencyReasoning}</p>}
                      {ai.timeConstraints && ai.timeConstraints.length > 0 && (
                        <ul className="mt-1 space-y-0.5">
                          {ai.timeConstraints.map((t, i) => (
                            <li key={i} className="flex items-center gap-1.5 text-xs text-red-600">
                              <Clock className="h-3 w-3 shrink-0" />{t}
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  </div>
                )}

                {/* Key Facts */}
                {ai.keyFacts && ai.keyFacts.length > 0 && (
                  <div>
                    <h3 className="text-sm font-semibold text-slate-900 mb-3 flex items-center gap-2">
                      <FileText className="h-4 w-4 text-indigo-500" />Key Facts
                    </h3>
                    <ul className="space-y-2">
                      {ai.keyFacts.map((fact, i) => (
                        <li key={i} className="flex items-start gap-2.5 text-sm text-slate-600">
                          <span className="w-5 h-5 rounded-full bg-indigo-100 text-indigo-700 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">{i + 1}</span>
                          {fact}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Recommended Actions */}
                {ai.recommendedActions && ai.recommendedActions.length > 0 && (
                  <div>
                    <h3 className="text-sm font-semibold text-slate-900 mb-3 flex items-center gap-2">
                      <CheckCircle2 className="h-4 w-4 text-emerald-500" />Recommended Actions
                    </h3>
                    <ul className="space-y-2">
                      {ai.recommendedActions.map((action, i) => (
                        <li key={i} className="flex items-start gap-2.5 text-sm text-slate-600">
                          <ChevronRight className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                          {action}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* Case References */}
                {ai.caseReferences && ai.caseReferences.length > 0 && (
                  <div>
                    <h3 className="text-sm font-semibold text-slate-900 mb-3 flex items-center gap-2">
                      <BookOpen className="h-4 w-4 text-violet-500" />Relevant Case References & Statutes
                    </h3>
                    <div className="space-y-3">
                      {ai.caseReferences.map((ref, i) => (
                        <div key={i} className="p-3.5 rounded-xl border border-slate-100 bg-slate-50">
                          <div className="flex items-start justify-between gap-2">
                            <p className="text-sm font-semibold text-slate-900">{ref.name}</p>
                            <div className="flex items-center gap-1 shrink-0">
                              <span className="text-xs text-slate-500 bg-white border border-slate-200 px-2 py-0.5 rounded-full">{ref.year}</span>
                              <span className="text-xs text-slate-500 bg-white border border-slate-200 px-2 py-0.5 rounded-full">{ref.court}</span>
                            </div>
                          </div>
                          <p className="text-xs text-slate-500 mt-1.5 leading-relaxed">{ref.relevance}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* ⚠ Statutory Warning */}
                <div className="flex items-start gap-3 p-4 bg-amber-50 border border-amber-200 rounded-xl">
                  <AlertTriangle className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm font-semibold text-amber-800">Statutory Disclaimer</p>
                    <p className="text-xs text-amber-700 mt-1 leading-relaxed">
                      This analysis is <strong>AI-generated</strong> and is provided for informational purposes only. It does not constitute legal advice and should not be relied upon as such. Case references and legal interpretations may not be fully accurate or applicable to your specific jurisdiction and circumstances. <strong>Please consult a qualified lawyer to establish accuracy and obtain advice tailored to your situation.</strong>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-8 text-center text-slate-400 text-sm">
              <Brain className="h-8 w-8 mx-auto mb-3 opacity-30" />
              AI analysis in progress — please check back in a moment.
            </div>
          )}

          {/* Lawyer Recommendations */}
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
            <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-2">
              <h2 className="font-semibold text-slate-900">Recommended Lawyers</h2>
              {legalCase.recommendations.length > 0 && (
                <span className="text-xs bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full font-medium">{legalCase.recommendations.length} matches</span>
              )}
            </div>
            {legalCase.recommendations.length === 0 ? (
              <div className="px-6 py-10 text-center text-slate-400 text-sm">
                {['DRAFT', 'SUBMITTED'].includes(legalCase.status)
                  ? 'AI is still matching lawyers for your case…'
                  : 'No lawyer matches found. Try broadening your location preference.'}
              </div>
            ) : (
              <div className="divide-y divide-slate-100">
                {legalCase.recommendations.map((rec, i) => {
                  const l = rec.lawyerProfile;
                  const score = Math.round(Number(rec.score) * 100);
                  return (
                    <div key={rec.id} className="flex items-center gap-4 px-6 py-4">
                      <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-700 text-xs font-bold shrink-0">
                        {l.firstName[0]}{l.lastName[0]}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="font-medium text-slate-900 text-sm">Adv. {l.firstName} {l.lastName}</p>
                        <p className="text-xs text-slate-400 mt-0.5">
                          {l.practiceAreas.map(a => a.practiceArea.name).join(', ')}
                          {l.city ? ` · ${l.city}` : ''} · {l.yearsOfExperience} yrs
                          {Number(l.averageRating) > 0 ? ` · ★ ${Number(l.averageRating).toFixed(1)}` : ''}
                        </p>
                      </div>
                      <div className="flex items-center gap-3 shrink-0">
                        {i === 0 && <span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full font-medium">Best Match</span>}
                        <div className="text-right">
                          <p className="text-xs text-slate-400">Match</p>
                          <p className="text-sm font-bold text-indigo-600">{score}%</p>
                        </div>
                        <Button size="sm" asChild className="bg-indigo-600 hover:bg-indigo-700 h-8 text-xs">
                          <Link href={`/lawyers/${l.slug}`}>Book ₹{Number(l.consultationFee).toLocaleString('en-IN')}</Link>
                        </Button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-5">
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
            <h2 className="font-semibold text-slate-900 text-sm mb-4">Case Details</h2>
            <div className="space-y-3 text-sm">
              {[
                { label: 'Case No.', value: legalCase.caseNumber },
                { label: 'Practice Area', value: legalCase.practiceArea?.name ?? '—' },
                { label: 'Status', value: legalCase.status.replace('_', ' ') },
                { label: 'Urgency', value: legalCase.urgency },
                { label: 'Complexity', value: ai.estimatedComplexity ?? '—' },
                { label: 'Filed', value: legalCase.createdAt.toLocaleDateString('en-IN') },
                { label: 'Lawyer Matches', value: `${legalCase.recommendations.length}` },
              ].map(({ label, value }) => (
                <div key={label} className="flex justify-between items-center">
                  <span className="text-slate-400">{label}</span>
                  <span className={`font-medium text-right text-xs ${label === 'Complexity' && value !== '—' ? `px-2 py-0.5 rounded-full ${complexityColor[value] ?? ''}` : 'text-slate-900'}`}>
                    {value}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {ai.riskFactors && ai.riskFactors.length > 0 && (
            <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5">
              <h2 className="font-semibold text-slate-900 text-sm mb-3 flex items-center gap-1.5">
                <AlertCircle className="h-4 w-4 text-orange-500" />Risk Factors
              </h2>
              <ul className="space-y-1.5">
                {ai.riskFactors.map((r, i) => (
                  <li key={i} className="text-xs text-slate-600 flex items-start gap-1.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-orange-400 shrink-0 mt-1.5" />{r}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5 space-y-2">
            <h2 className="font-semibold text-slate-900 text-sm mb-3">Actions</h2>
            <Button className="w-full bg-indigo-600 hover:bg-indigo-700 justify-start gap-2 h-9 text-sm" asChild>
              <Link href="/client/consultations"><Calendar className="h-4 w-4" />Schedule Consultation</Link>
            </Button>
            <Button variant="outline" className="w-full justify-start gap-2 h-9 text-sm" asChild>
              <Link href="/client/documents"><FileText className="h-4 w-4" />Upload Documents</Link>
            </Button>
            <Button variant="outline" className="w-full justify-start gap-2 h-9 text-sm" asChild>
              <Link href="/client/messages"><MessageSquare className="h-4 w-4" />Message Lawyer</Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
